project:
  type: website
  output-dir: docs
  
website:
  title: "Ohio Urban Renewal Explorer"
  page-footer:
    left: "Â© 2025 Sujan Kakumanu | MUSA 5500 Final Project"
    right: 
      - text: "University of Pennsylvania Weitzman School of Design"
  navbar:
    background: primary
    search: true
    left:
      - text: "Technical Report"
        href: report.qmd
      - text: "Interactive Component"
        href: interactive.ipynb
      - text: "Exploratory Code"
        menu:
          - text: "Aerial Imagery"
            href: exploratory-analysis/historical-aerial-imagery.ipynb
          - text: "Historical Census Data"
            href: exploratory-analysis/census-data.ipynb
          - text: "OSMnx of Streets"
            href: exploratory-analysis/osmnx-exploration.ipynb
    
    right:
      - icon: github
        href: https://github.com/kakumanus/urban-renewal-explorer
        aria-label: GitHub

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "On This Page"
    code-fold: true
    code-tools: true
    code-copy: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: true
    anchor-sections: true
    fig-cap-location: bottom
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px

execute:
  freeze: auto
  cache: false
  warning: false
  message: false

